# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Nexmark tests using Direct Runner.

name: PostCommit Java Nexmark Direct Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: ['master', 'release-*']
    tags: 'v*'
permissions: read-all

jobs:
  set-properties:
    runs-on: self-hosted
    outputs:
      properties: ${{ steps.test-properties.outputs.properties }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: test-properties
        uses: ./.github/actions/setup-default-test-properties

  java-postcommit-nexmark-direct:
    needs: set-properties
    name: Run PostCommit Java Nexmark - Direct Runner
    runs-on: [self-hosted, ubuntu-20.04]
    strategy:
      fail-fast: false
      matrix:
        streaming: ["true","false"]
        querytype: ["","--queryLanguage=sql","--queryLanguage=zetasql"]
    timeout-minutes: 240
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false        
      - name: Run Nexmark with Straming  Mode=${{matrix.streaming}} with Direct runner
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: >
            :sdks:java:testing:nexmark:run -Pnexmark.runner=:runners:direct-java 
            -Pnexmark.args=" 
              --runner=DirectRunner 
              --bigQueryTable=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.BIGQUERY_TABLE}}
              --bigQueryDataset=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.BIGQUERY_DATASET}}
              --project=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.PROJECT}}
              --resourceNameMode=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.RESOURCE_NAMEMODE}}
              --exportSummaryToBigQuery=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.EXPORT_SUMMARY_TO_BIGQUERY}}
              --tempLocation=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.TEMP_LOCATION}}
              --influxDatabase=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.INFLUX_DATABASE}}
              --influxHost=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.INFLUX_HOST}}
              --baseInfluxMeasurement=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.BASE_INFLUX_MEASUREMENT}}
              --exportSummaryToInfluxDB=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.EXPORT_SUMMARY_TO_INFLUXDB}}
              --influxRetentionPolicy=${{fromJson(needs.set-properties.outputs.properties).NexmarkTestsProperties.INFLUX_RETENTION_POLICY}}
              --streaming=${{matrix.streaming}} 
              --suite=SMOKE 
              --manageResources=false 
              --monitorJobs=true 
              --enforceEncodability=true 
              --enforceImmutability=true 
              ${{matrix.queryType}}"
