# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: PostCommit Java examples Dataflow Java 11,17

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: ['master', 'release-*']
    tags: 'v*'
  pull_request:
    branches: ['master', 'release-*']
    tags: 'v*'
    paths: []


jobs:
  python-portable-commit:
    name: Run PostCommit Java examples Dataflow Java 11,17
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        java_version: ['11','17']
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
      - name: Get Run time available Processors
        run : echo "AVAILABLE_PROCESSORS=$((3* $(grep -c ^processor /proc/cpuinfo)))" >> $GITHUB_ENV
      - name: Run :runners:google-cloud-dataflow-java:examples:java${{ matrix.java_version}}PostCommit
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :runners:google-cloud-dataflow-java:examples:java${{ matrix.java_version}}PostCommit --max-workers=${{env.AVAILABLE_PROCESSORS}}
          