# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This workflow will update python dependencies as part of the release process
# And commit the changes into the branch release

name: Update Python Depedencies

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        description: Name of the new branch that will contain the changes 
        required: true
permissions: read-all

jobs:
  set-properties:
    #runs-on: [self-hosted, ubuntu-20.04]
    runs-on: ubuntu-latest
    outputs:
      properties: ${{ steps.test-properties.outputs.properties }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false        
      - id: test-properties
        uses: ./.github/actions/setup-default-test-properties

  update_python_dependencies:
    #runs-on: [self-hosted, ubuntu-20.04]
    runs-on: ubuntu-latest
    needs: set-properties
    name: Update Python Dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Setup environment
        uses: ./.github/actions/setup-self-hosted-action
      - name: Update Python Dependencies
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :sdks:python:container:generatePythonRequirementsAll
          arguments: "-Pposargs=${{env.tests}}"
      
  commit_changes:
    #runs-on: [self-hosted, ubuntu-20.04]
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.inputs.BRANCH_NAME }}
    needs: update_python_dependencies
    name: Commit Git Changes
    steps:
      - name: Install gh cli
        uses: ./.github/actions/setup-gh-cli-linux
      - name: Set git config
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email actions@"$RUNNER_NAME".local
      - name: Commit Changes and create new PR
        run: |
          git checkout -b ${{env.BRANCH_NAME}}
          git add -A 
          git commit -m "Update Python Dependencies" --quiet
          git push --set-upstream origin ${{ env.BRANCH_NAME}} --quiet
          GITHUB_PR_URL=$(gh pr create --title "Update Python Dependencies from BRANCH ${{ env.BRANCH_NAME }}" --body "This PR was create using the update python dependencies from branch ${{ env.BRANCH_NAME }}")
          echo "Link of the new PR  $GITHUB_PR_URL "







    
